// <auto-generated />
namespace DemoParking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcolisticket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolisticket));
        
        string IMigrationMetadata.Id
        {
            get { return "202306030214320_add-col-isticket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
